configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmVkMjljOWZiODM0N2IzYmE3NmY4ZjBkYjY5MjI2MDE5MzlhMDhhNzk0NDlmZDJlNmNiNmM3NDkyNWJkZGYwMjE2MzUxNzQ1MDExYzAwOGE4ZWNmM2IyZjliZmNmNGYwMmYwYmI5OGY3NjIwZmMyY2JmZTFhNTU5M2UzYzA0OGU=
